### ISSUE TITLE
Docs: Removed bs4 examples in favor of bs5

### ISSUE THREAD

**Issue by mandrasch** [NickDJM/accessible-menu-bootstrap-4#24]
Hey, just wanted to let you know that I removed bootstrap4 from https://github.com/mandrasch/accessible-menu-bootstrap-examples. 

I rewrote the project with laravel-mix compiler and can't include bs4 and bs5 at same time by now.  Guess people use bootstrap5 most of the time now anyways. 

Best regards

**Comment by NickDJM** [comment]
@mandrasch Cool, thanks for letting me know!

I'll remove it from this particular repo and make sure its pushed up to the BS5 project.

**Comment by NickDJM** [comment]
Removed and merged.
